spring:
  application:
    name: ${SPRING_APP_NAME}
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    virtual-host: ${RABBITMQ_VHOST}
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

server:
  port: ${SERVER_PORT}

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  override-with-generic-response: false
  packagesToScan: com.smshub.org

resilience4j:
  ratelimiter:
    instances:
      smsRateLimiter:
        limitForPeriod: 4
        limitRefreshPeriod: 1s
        timeoutDuration: 0

orange:
  sms:
    client:
      id: ${ORANGE_SMS_CLIENT_ID}
      secret: ${ORANGE_SMS_CLIENT_SECRET}
    auth:
      header: ${ORANGE_SMS_AUTH_HEADER}
    sender:
      number: ${ORANGE_SMS_SENDER_NUMBER}
    token:
      url: ${ORANGE_SMS_TOKEN_URL}
    send:
      url: ${ORANGE_SMS_SEND_URL}
